### ISSUE TITLE
Arabic Translation issue

### ISSUE THREAD

**Issue by maltourky** [billchen198318/bamboobsc7#2]
Dear Chen,
consider changing the following in all arabic files as the current translation is correct but this more accurate
do the following exactly as it is with `_clear=` to not affect other words has the same letters.
replace all  *`_clear=\u0645\u062D\u0648`*  to  *`_clear=\u0645\u0633\u062D`*

also there is one mistake ( two variables ) need to be fixed in file __EmployeeManagementAction_ar.properties__

the variables with the suffix  *`_password1`* in the mentioned file only, has a wrong value.
it should be *`_password1=\u0643\u0644\u0645\u0629 \u0627\u0644\u0645\u0631\u0648\u0631`* not *`_password1=\u0645\u062D\u0648`*
so please consider changing it and sorry for that ;)

**Comment by billchen198318** [comment]
Thanks, will patch to bambooBSC7 repository. https://github.com/billchen198318/bamboobsc7

**Comment by billchen198318** [comment]
Patch ok , https://github.com/billchen198318/bamboobsc7/commit/bc1158c320834886727c1d8f616502567d8dd31f 

thanks.
