### ISSUE TITLE
just an idea 

### ISSUE THREAD

**Issue by maltourky** [billchen198318/bamboobsc7#3]
hello Chen,

i think this would be added value to the system if you try to support FilteringSelect in the GSTag so can be used with the long containing data lists. :)

**Comment by billchen198318** [comment]
This idea is good, but there are a lot of 0.7.0 development projects did not complete
This part will be discussed later

**Comment by billchen198318** [comment]
I just finished the history item score line chart report today, Currently there is no extra time to develop other things.

Thanks

**Comment by billchen198318** [comment]
Add FilteringSelect tab. https://github.com/billchen198318/bamboobsc7/commit/0389527199c1375153e20ef539f19f5a8dff806d

**Comment by maltourky** [comment]
Dear Bill,

did you test it on linked lists., as i tried to test it before on kpi-managment.jsp for vision list and Objectives, and Perspectives as they linked to each other the home.js file return error and the list has not been populated.
```JAVA
Uncaught TypeError: destSelect.getOptions is not a function home.js  line:602
```

i think the issue is with the ftl file there should be input somewhere in it as the html output of the select is different from the filteringselect. so i think either change the js file or the ftl file should be change accordingly.

thanks.

**Comment by billchen198318** [comment]
beacuse kpi-managment select options will use XHR to tigger change item.
you need change home.js method code, please refence http://stackoverflow.com/questions/5707021/dijit-form-filteringselect-dynamically-change-options

you need do it by youself.

bye
